### ISSUE TITLE
Template for VKB-Sim Gladiator NXT not found

### ISSUE THREAD

**Issue by Sturmovik-ice** [Rexeh/joystick-diagrams#41]
As the title says, hope the following screenshots will suffice to describe the problem:

![Program](https://user-images.githubusercontent.com/76632483/103176524-5a152300-486a-11eb-9c16-6473a2b7a037.png)

![Template](https://user-images.githubusercontent.com/76632483/103176538-67321200-486a-11eb-80e5-29a91c0fd414.png)

![Input Folder](https://user-images.githubusercontent.com/76632483/103176541-6e592000-486a-11eb-8246-30760c3ff609.png)

**Comment by Rexeh** [comment]
Thanks this is a.known issue with VKB rather than this tool, they inserted a blank space at the start of the device name.

This is fixed in the next version

**Comment by Rexeh** [comment]
Duplicate issue - https://github.com/Rexeh/joystick-diagrams/issues/36

Thanks for reporting

**Comment by doerek** [comment]
i'm getting the same error when using my Star Citizen Profile and my Dual T.16000M

![image](https://user-images.githubusercontent.com/2093684/113402441-49160980-93a5-11eb-9361-911f9d219dce.png)

**Comment by Rexeh** [comment]
> i'm getting the same error when using my Star Citizen Profile and my Dual T.16000M
> 
> ![image](https://user-images.githubusercontent.com/2093684/113402441-49160980-93a5-11eb-9361-911f9d219dce.png)

Hi Doerek, not sure why it's not finding a template but dual T.16000M is not supported due to the way SC handles joystick GUIDs.

See **known issues** on
https://joystick-diagrams.com/changelog/version-1-4-0-star-citizen.html

To fix, people will need to lobby Star Citizen to ensure the GUID in the config file is the actual windows device GUID, not the manufacturer/model style guid which just tells you the brand of stick.

On the above, you're welcome to set debug level to 3 in the config file, and post on support discord for me to have a look at.
